CREATE TABLE IF NOT EXISTS `DW_OPEN_ACCESS_LOG`
(
    `ID`            INT(11) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
    `APP_ID`        VARCHAR(32) DEFAULT NULL COMMENT '访问者APPID',
    `SEQ_NO`        VARCHAR(32) DEFAULT NULL COMMENT '请求流水',
    `ACCESS_METHOD` VARCHAR(32) DEFAULT NULL COMMENT '访问方法',
    `VERSION`       VARCHAR(32) DEFAULT NULL COMMENT '版本',
    `RESULT_CODE`   INT(11)     DEFAULT NULL COMMENT '返回码',
    `RESULT_ROW`    INT(11)     DEFAULT NULL COMMENT '返回数据记录数',
    `CREATE_TIME`   DATETIME    DEFAULT NULL,
    `UPDATE_TIME`   DATETIME    DEFAULT NULL,
    `ELAPSED`       INT(11)     DEFAULT NULL COMMENT '处理时间',
    PRIMARY KEY (`ID`),
    KEY `ACCESS_TIME` (`CREATE_TIME`)
) ENGINE = INNODB
  AUTO_INCREMENT = 1
  DEFAULT CHARSET = UTF8 COMMENT ='开放接口访问日志';
CREATE TABLE IF NOT EXISTS `DW_OPEN_ACCESS_STATISTICS`
(
    `ID`            INT(11) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
    `STAT_TYPE`     INT(11)     DEFAULT NULL COMMENT '统计类型',
    `ACCESS_METHOD` VARCHAR(64) DEFAULT NULL COMMENT '访问方法',
    `DATA_TIME`     DATETIME    DEFAULT NULL,
    `STAT_TIME`     DATETIME    DEFAULT NULL COMMENT '统计时间',
    `RESULT_CODE`   INT(11)     DEFAULT NULL COMMENT '返回编码',
    `RESULT`        MEDIUMTEXT COMMENT '统计结果',
    PRIMARY KEY (`ID`),
    KEY `ACC_STAT_TIME` (`STAT_TIME`)
) ENGINE = INNODB
  AUTO_INCREMENT = 1
  DEFAULT CHARSET = UTF8 COMMENT ='API调用情况统计';
CREATE TABLE `DW_OPEN_API_CONDITION` (
                                         `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
                                         `DATA_ASSET_ID` int(11) DEFAULT NULL COMMENT '数据资产ID',
                                         `ASSET_COLUMNS` varchar(64) DEFAULT NULL COMMENT '对应列',
                                         `ASSET_DATATYPE` varchar(32) DEFAULT NULL COMMENT '数据类型',
                                         `ASSET_COLUMNS_LENGTH` int(11) DEFAULT NULL COMMENT '长度',
                                         `DESCRIPTIONS` varchar(255) DEFAULT NULL COMMENT '描述',
                                         `REQUIRED` tinyint(4) DEFAULT '0' COMMENT '是否必须',
                                         `SAMPLE` varchar(255) DEFAULT NULL COMMENT '样例',
                                         `CREATE_TIME` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
                                         `UPDATE_TIME` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                         `TYPE` int(11) DEFAULT NULL COMMENT '数据类型',
                                         `MULTI_VALUE` tinyint(255) DEFAULT '0' COMMENT '是否支持多值',
                                         PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='API访问参数';
CREATE TABLE IF NOT EXISTS `DW_OPEN_APPROVAL`
(
    `APPROVAL_ID`            INT(11)      NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `USER_IDENTIFICATION`    VARCHAR(255) NOT NULL COMMENT '创建审批单的用户标识',
    `APPROVAL_SUBJECT`       VARCHAR(255) NOT NULL COMMENT '审批主体',
    `APPROVAL_BUSINESS_TYPE` TINYINT(4)   NOT NULL COMMENT '审批的业务',
    `APPROVAL_BODY`          TEXT         NOT NULL COMMENT '审批内容',
    `APPROVAL_STATUS`        TINYINT(4)   NOT NULL COMMENT '审批状态(0 新建 1 审批中 2 审批通过 3 审批失败)',
    `APPROVAL_MESSAGE`       VARCHAR(2048) DEFAULT NULL COMMENT '审批信息',
    `UPDATE_TIME`            DATETIME     NOT NULL,
    `CREATE_TIME`            DATETIME     NOT NULL,
    PRIMARY KEY (`APPROVAL_ID`)
) ENGINE = INNODB
  AUTO_INCREMENT = 1
  DEFAULT CHARSET = UTF8 COMMENT '审批表';
CREATE TABLE IF NOT EXISTS `DW_OPEN_APP_ACCESS`
(
    `DATA_ACCESS_APP_ID`      INT(11)      NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `DATA_ACCESS_APP_NAME`    VARCHAR(255) NOT NULL COMMENT '数据访问客户端',
    `DATA_ACCESS_KEY`         VARCHAR(255) NOT NULL,
    `DATA_ACCESS_SECRET`      VARCHAR(255) NOT NULL COMMENT '数据访问密钥',
    `DATA_ACCESS_DESCRIPTION` VARCHAR(255) NOT NULL,
    `UPDATE_TIME`             DATETIME     NOT NULL,
    `CREATE_TIME`             DATETIME     NOT NULL,
    `IN_CHARGE`               VARCHAR(32) DEFAULT NULL COMMENT '负责人',
    PRIMARY KEY (`DATA_ACCESS_APP_ID`)
) ENGINE = INNODB
  AUTO_INCREMENT = 1
  DEFAULT CHARSET = UTF8 COMMENT ='数据访问接入端';
CREATE TABLE IF NOT EXISTS `DW_OPEN_APP_ACCESS_RULE`
(
    `DATA_ACCESS_RULE_ID`   INT(11)      NOT NULL AUTO_INCREMENT COMMENT '自增ID',
    `DATA_ASSET_API_ID`     INT(11)      NOT NULL COMMENT '所属数据源ID',
    `DATA_ACCESS_APP_ID`    INT(11)      NOT NULL COMMENT '外键 访问数据客户端标识',
    `DATA_ASSET_FIELD_NAME` VARCHAR(255) NOT NULL COMMENT '所属数据源下表的列名称',
    `UPDATE_TIME`           DATETIME     NOT NULL,
    `CREATE_TIME`           DATETIME     NOT NULL,
    PRIMARY KEY (`DATA_ACCESS_RULE_ID`)
) ENGINE = INNODB
  AUTO_INCREMENT = 1
  DEFAULT CHARSET = UTF8 COMMENT ='数据访问规则';

CREATE TABLE `DW_OPEN_DATA_ASSET_API`
(
    `DATA_ASSET_API_ID`         int(11)      NOT NULL AUTO_INCREMENT COMMENT '自增ID',
    `DATA_ASSET_NAME`           varchar(255) NOT NULL COMMENT '数据资产名称',
    `DATA_ASSET_DESCRIPTION`    varchar(255) NOT NULL DEFAULT '' COMMENT '数据资产描述',
    `IN_CHARGE`                 varchar(255) NOT NULL DEFAULT '' COMMENT '负责人(标识1,标识2,标识3)',
    `DATA_ASSET_PUBLISH_STATUS` tinyint(4)   NOT NULL COMMENT '数据资产状态',
    `DATA_ASSET_API_METHOD`     varchar(255) NOT NULL COMMENT '数据资产API名称',
    `UPDATE_TIME`               datetime     NOT NULL,
    `CREATE_TIME`               datetime     NOT NULL,
    `ICON_URL`                  varchar(512)          DEFAULT NULL COMMENT '图标路径',
    `API_NAME`                  varchar(32)           DEFAULT NULL COMMENT 'API名称',
    `UPDATE_FREQUENCY`          int(11)               DEFAULT NULL COMMENT '更新频率',
    `PROTOCOL`                  int(11)               DEFAULT NULL COMMENT '请求协议',
    `PRIVATE`                   tinyint(4)            DEFAULT NULL COMMENT '是否加密',
    `API_GROUP_ID`              int(11)               DEFAULT NULL COMMENT '分组ID',
    `API_DESCRIPTION`           varchar(1024)         DEFAULT NULL COMMENT 'API描述',
    `RESPONSE_CONTENT_TYPE`     varchar(255)          DEFAULT NULL COMMENT '返回格式',
    `REQ_METHOD`                varchar(255)          DEFAULT '' COMMENT '请求方法',
    `DATASOURCE_CONFIG_ID`      int(11)               DEFAULT NULL COMMENT '数据源配置ID',
    PRIMARY KEY (`DATA_ASSET_API_ID`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8 COMMENT ='数据资产API';
CREATE TABLE IF NOT EXISTS `DW_OPEN_FR_CRYSTAL`
(
    `FR_CRYSTAL_ID`         INT(11)      NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `FR_CRYSTAL_OUTSIDE_ID` VARCHAR(255) NOT NULL COMMENT '帆软外部水晶球ID',
    `USER_IDENTIFICATION`   VARCHAR(255) NOT NULL COMMENT '所属员工标识',
    `SELECT_STATUS`         TINYINT(4)   NOT NULL COMMENT '选择状态(0: 未选 1: 已经)',
    `FR_CRYSTAL_ORDER`      INT(255)     NOT NULL DEFAULT '1' COMMENT '水晶球排序',
    `UPDATE_TIME`           DATETIME     NOT NULL,
    `CREATE_TIME`           DATETIME     NOT NULL,
    `CRYSTAL_DETAIL_ID`     INT(11)               DEFAULT NULL COMMENT '报表ID',
    PRIMARY KEY (`FR_CRYSTAL_ID`),
    KEY `IDX_CRYSTAL_USER_IDFY` (`USER_IDENTIFICATION`) USING BTREE
) ENGINE = INNODB
  AUTO_INCREMENT = 1
  DEFAULT CHARSET = UTF8 COMMENT '水晶球用户关联';
CREATE TABLE IF NOT EXISTS `DW_OPEN_FR_CRYSTAL_DETAILS`
(
    `ID`                    INT(11) NOT NULL AUTO_INCREMENT,
    `FR_CRYSTAL_OUTSIDE_ID` VARCHAR(255)  DEFAULT NULL COMMENT '帆软外部水晶球ID',
    `FR_CRYSTAL_ICON`       BLOB COMMENT '项目图标',
    `PROJECT_INTRODUCE`     VARCHAR(255)  DEFAULT NULL COMMENT '项目日报介绍',
    `SUITABLE_OBJECT`       VARCHAR(255)  DEFAULT NULL COMMENT '适用者',
    `DESIGNER`              VARCHAR(255)  DEFAULT NULL COMMENT '设计者',
    `BACKGROUND_ICON`       MEDIUMBLOB COMMENT '背景缩略图',
    `FR_CRYSTAL_NAME`       VARCHAR(64)   DEFAULT NULL COMMENT '报表名称',
    `FR_CRYSTAL_URL`        VARCHAR(64)   DEFAULT NULL COMMENT '报表地址',
    `BACKGROUND_ICON_URL`   VARCHAR(1024) DEFAULT NULL COMMENT '背景图片URL地址',
    `CREATE_TIME`           DATETIME      DEFAULT NULL COMMENT '创建时间',
    `UPDATE_TIME`           DATETIME      DEFAULT NULL COMMENT '更新时间',
    `DATA_TYPE`             VARCHAR(64)   DEFAULT NULL COMMENT '数据类型',
    `GROUP_ID`              INT(11)       DEFAULT NULL COMMENT '分组ID',
    PRIMARY KEY (`ID`)
) ENGINE = INNODB
  AUTO_INCREMENT = 1
  DEFAULT CHARSET = UTF8 COMMENT '水晶球报表详情';
CREATE TABLE IF NOT EXISTS `DW_OPEN_FR_CRYSTAL_GROUP`
(
    `ID`          INT(11) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
    `GROUP_NAME`  VARCHAR(32) DEFAULT NULL COMMENT '组名',
    `CREATE_TIME` DATETIME    DEFAULT NULL COMMENT '创建时间',
    `UPDATE_TIME` DATETIME    DEFAULT NULL COMMENT '修改时间',
    PRIMARY KEY (`ID`)
) ENGINE = INNODB
  AUTO_INCREMENT = 1
  DEFAULT CHARSET = UTF8 COMMENT '水晶球分组';
CREATE TABLE IF NOT EXISTS `DW_OPEN_FR_CRYSTAL_RECORD`
(
    `ID`         INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `USERID`     VARCHAR(20) DEFAULT NULL,
    `VISIT_TIME` DATETIME    DEFAULT NULL,
    PRIMARY KEY (`ID`)
) ENGINE = INNODB
  AUTO_INCREMENT = 1
  DEFAULT CHARSET = UTF8 COMMENT '水晶球第一次访问记录';

CREATE TABLE IF NOT EXISTS `DW_OPEN_OPTIMISTIC_LOCK`
(
    `ID`          INT(11) NOT NULL AUTO_INCREMENT COMMENT '锁ID',
    `LOCK_NAME`   VARCHAR(20) DEFAULT NULL COMMENT '锁名字',
    `IP`          VARCHAR(20) DEFAULT NULL COMMENT '占用的IP',
    `LOCK_STATUS` SMALLINT(6) DEFAULT NULL COMMENT '锁状态',
    `VERSION_NO`  INT(11)     DEFAULT NULL COMMENT '锁版本号',
    `CREATE_TIME` DATETIME    DEFAULT NULL COMMENT '创建时间',
    `UPDATE_TIME` DATETIME    DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (`ID`)
) ENGINE = INNODB
  AUTO_INCREMENT = 1
  DEFAULT CHARSET = UTF8 COMMENT ='乐观锁';
CREATE TABLE IF NOT EXISTS `DW_OPEN_USER`
(
    `ID`              INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `USER`            VARCHAR(50) DEFAULT NULL COMMENT '用户名',
    `DISPLAY_NAME`    VARCHAR(50) DEFAULT NULL COMMENT '姓名',
    `EMPLOYEE_NUMBER` VARCHAR(20) DEFAULT NULL COMMENT '工号',
    `AREA`            VARCHAR(50) DEFAULT NULL COMMENT '区域',
    `PROJECT`         VARCHAR(50) DEFAULT NULL COMMENT '项目',
    `ROLE_ID`         TINYINT(2)  DEFAULT NULL COMMENT '角色类型 1管理员 2普通用户',
    `CREATE_TIME`     DATETIME    DEFAULT NULL,
    `UPDATE_TIME`     DATETIME    DEFAULT NULL,
    PRIMARY KEY (`ID`)
) ENGINE = INNODB
  AUTO_INCREMENT = 1
  DEFAULT CHARSET = UTF8 COMMENT '用户';
CREATE TABLE IF NOT EXISTS `DW_OPEN_USER_INFO`
(
    `ZEMPL`     VARCHAR(256) DEFAULT NULL COMMENT '主数据编码',
    `TXTMI`     VARCHAR(256) DEFAULT NULL,
    `ZACCTGDEP` VARCHAR(256) DEFAULT NULL COMMENT '核算部门名称',
    `ZACCTGDID` VARCHAR(256) DEFAULT NULL COMMENT '核算部门编码',
    `ZACCTGID`  VARCHAR(256) DEFAULT NULL COMMENT '核算公司编码',
    `ZACCTGORG` VARCHAR(256) DEFAULT NULL COMMENT '核算组织名称',
    `ZBACKUP1`  VARCHAR(256) DEFAULT NULL,
    `ZBACKUP2`  VARCHAR(256) DEFAULT NULL,
    `ZBACKUP3`  VARCHAR(256) DEFAULT NULL,
    `ZBACKUP4`  VARCHAR(256) DEFAULT NULL,
    `ZBACKUP5`  VARCHAR(256) DEFAULT NULL,
    `ZBACKUP6`  VARCHAR(256) DEFAULT NULL,
    `ZBEGDA`    VARCHAR(256) DEFAULT NULL COMMENT '入职时间',
    `ZBNKACCT`  VARCHAR(256) DEFAULT NULL COMMENT '银行账号',
    `ZBNKACCTN` VARCHAR(256) DEFAULT NULL COMMENT '户名',
    `ZBNKCDE`   VARCHAR(256) DEFAULT NULL COMMENT '银行联行号',
    `ZBNKNA`    VARCHAR(256) DEFAULT NULL COMMENT '开户行名称',
    `ZBSECTOR`  VARCHAR(256) DEFAULT NULL COMMENT '业务板块',
    `ZBUDDEPT`  VARCHAR(256) DEFAULT NULL COMMENT '预算部门名称',
    `ZBUDEPTID` VARCHAR(256) DEFAULT NULL COMMENT '预算部门编码',
    `ZBUDID`    VARCHAR(256) DEFAULT NULL COMMENT '预算单位编码',
    `ZBUDORG`   VARCHAR(256) DEFAULT NULL COMMENT '预算组织名称',
    `ZCOTAG`    VARCHAR(256) DEFAULT NULL COMMENT '公司标记',
    `ZGEBDT`    VARCHAR(256) DEFAULT NULL COMMENT '出生日期',
    `ZGESCH`    VARCHAR(256) DEFAULT NULL COMMENT '性别',
    `ZHREMPLID` VARCHAR(256) DEFAULT NULL COMMENT 'SAP编码',
    `ZISMARKET` VARCHAR(256) DEFAULT NULL COMMENT '是否营销',
    `ZLEADA`    VARCHAR(256) DEFAULT NULL COMMENT '离职日期',
    `ZNACHN`    VARCHAR(256) DEFAULT NULL COMMENT '姓名',
    `ZNAEN`     VARCHAR(256) DEFAULT NULL COMMENT '人员英文名称',
    `ZNATI`     VARCHAR(256) DEFAULT NULL COMMENT '国籍',
    `ZNCEMPLID` VARCHAR(256) DEFAULT NULL COMMENT 'NC人员编码',
    `ZORGID`    VARCHAR(256) DEFAULT NULL COMMENT '组织编码',
    `ZORGNAME`  VARCHAR(256) DEFAULT NULL COMMENT '组织名称',
    `ZOTGNG`    VARCHAR(256) DEFAULT NULL COMMENT '是否已申请离职',
    `ZOVERSEA`  VARCHAR(256) DEFAULT NULL COMMENT '是否海外',
    `ZPERNR`    VARCHAR(256) DEFAULT NULL COMMENT '员工编码',
    `ZPERSG`    VARCHAR(256) DEFAULT NULL COMMENT '人员类别',
    `ZPOSTID`   VARCHAR(256) DEFAULT NULL COMMENT '岗位编码',
    `ZPOSTNAME` VARCHAR(256) DEFAULT NULL COMMENT '岗位名称',
    `ZSALECTR`  VARCHAR(256) DEFAULT NULL COMMENT '是否案场',
    `ZSTAT2`    VARCHAR(256) DEFAULT NULL COMMENT '人员状态',
    `ZSTATUS`   VARCHAR(256) DEFAULT NULL COMMENT '冻结状态(标识',
    `ZUSPNID`   VARCHAR(256) DEFAULT NULL COMMENT '手机',
    `ZUSRID`    VARCHAR(256) DEFAULT NULL COMMENT 'BIP账号',
    `ZWERKS`    VARCHAR(256) DEFAULT NULL COMMENT '人事范围'
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8 COMMENT '客户用户表';
CREATE TABLE IF NOT EXISTS `DW_OPEN_USER_MENUS`
(
    `ID`             INT(11)             NOT NULL AUTO_INCREMENT,
    `MENU_NAME`      VARCHAR(50)                  DEFAULT NULL COMMENT '菜单名称',
    `LINK`           VARCHAR(50)                  DEFAULT NULL COMMENT '菜单地址',
    `PARENT_MENU_ID` INT(11)                      DEFAULT NULL COMMENT '父菜单ID',
    `ICON`           VARCHAR(50)                  DEFAULT NULL,
    `ROLE_ID`        INT(11)                      DEFAULT NULL COMMENT '角色ID',
    `ORDER`          TINYINT(3)                   DEFAULT NULL COMMENT '排序',
    `CREATE_TIME`    DATETIME                     DEFAULT NULL,
    `CREATE_USER`    VARCHAR(50)                  DEFAULT NULL,
    `UPDATE_TIME`    DATETIME                     DEFAULT NULL,
    `UPDATE_USER`    VARCHAR(50)                  DEFAULT NULL,
    `LEVEL`          TINYINT(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '菜单层级',
    `IS_PUBLISH`     TINYINT(2)          NOT NULL DEFAULT '1' COMMENT '菜单是否开启 0否，1是',
    PRIMARY KEY (`ID`)
) ENGINE = INNODB
  AUTO_INCREMENT = 1
  DEFAULT CHARSET = UTF8 COMMENT '用户菜单';

CREATE TABLE IF NOT EXISTS `DW_OPEN_USER_PAGE_ACTION`
(
    `PAGE_RESOURCE` VARCHAR(255) NOT NULL COMMENT '资源标识(AAA.BBB.CCC)',
    `PAGE_EVENT`    VARCHAR(32)  NOT NULL COMMENT '事件标识',
    `ACTION_USER`   VARCHAR(255) NOT NULL COMMENT '用户标识',
    `ACTION_TIME`   DATETIME     NOT NULL COMMENT '埋点行为时间',
    `UPDATE_TIME`   DATETIME     NOT NULL,
    `CREATE_TIME`   DATETIME     NOT NULL,
    `TIME_STAMP`    BIGINT(20) DEFAULT NULL
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8 COMMENT ='用户页面行为埋点';
CREATE TABLE IF NOT EXISTS `DW_OPEN_USER_ROLE`
(
    `ID`          INT(11)            NOT NULL AUTO_INCREMENT,
    `ROLE_NAME`   VARCHAR(20)                 DEFAULT NULL COMMENT '角色名称',
    `CREATE_TIME` DATETIME                    DEFAULT NULL,
    `CREATE_USER` VARCHAR(50)                 DEFAULT NULL,
    `UPDATE_TIME` DATETIME                    DEFAULT NULL,
    `UPDATE_USER` VARCHAR(50)                 DEFAULT NULL,
    `ROLE_TYPE`   BIGINT(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '0,非PBI角色 1 PBI系统管理员 2 PBI模块管理员 3 PBI报表浏览用户',
    PRIMARY KEY (`ID`)
) ENGINE = INNODB
  AUTO_INCREMENT = 1
  DEFAULT CHARSET = UTF8 COMMENT '用户DW_OPEN_USER_PAGE_ACTION角色';

CREATE TABLE IF NOT EXISTS `DW_OPEN_WHITE_LIST`
(
    `ID`                   INT(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `DATA_ACCESS_APP_ID`   INT(11)     DEFAULT NULL COMMENT '接入方ID',
    `IP`                   VARCHAR(32) DEFAULT NULL COMMENT '允许的IP地址',
    `DATA_ACCESS_APP_NAME` VARCHAR(64) DEFAULT NULL COMMENT '接入名称',
    `CREATE_TIME`          DATETIME    DEFAULT NULL COMMENT '创建时间',
    `UPDATE_TIME`          DATETIME    DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (`ID`)
) ENGINE = INNODB
  AUTO_INCREMENT = 1
  DEFAULT CHARSET = UTF8;


CREATE TABLE DW_OPEN_DEV_TOOL
(
    ID          INT PRIMARY KEY AUTO_INCREMENT COMMENT '自增主键',
    TOOL_NAME   VARCHAR(32) COMMENT '工具名称',
    TYPE_NAME   VARCHAR(32) COMMENT '分类名称',
    ICON_URL    VARCHAR(1024) COMMENT '图标地址',
    TOOL_URL    VARCHAR(1024) COMMENT '链接URL',
    DESCRIPTION VARCHAR(1024) COMMENT '工具描述',
    CREATE_TIME DATETIME COMMENT '创建时间',
    UPDATE_TIME DATETIME COMMENT '更新时间'
) ENGINE = INNODB
  CHARSET = UTF8
  COLLATE = UTF8_GENERAL_CI COMMENT '开发工具';


CREATE TABLE `DW_OPEN_OPERATOR_LOG`
(
    `ID`                  INT(11) NOT NULL AUTO_INCREMENT COMMENT ' 自增主键',
    `DESCRIPTION`         VARCHAR(32)   DEFAULT NULL,
    `CLASS_NAME`          VARCHAR(128)  DEFAULT NULL COMMENT '调用类',
    `METHOD_NAME`         VARCHAR(64)   DEFAULT NULL COMMENT '调用方法',
    `USER_IDENTIFICATION` VARCHAR(32)   DEFAULT NULL COMMENT '用户',
    `PARAMETER`           VARCHAR(2048) DEFAULT NULL COMMENT '请求参数',
    `CREATE_TIME`         DATETIME      DEFAULT NULL COMMENT '创建时间',
    `UPDATE_TIME`         DATETIME      DEFAULT NULL COMMENT '修改时间',
    `RESPONSE`            VARCHAR(2048) DEFAULT NULL COMMENT '返回结果',
    PRIMARY KEY (`ID`),
    KEY `OPERATOR_INDEX` (`CREATE_TIME`) COMMENT '操作日志时间索引'
) ENGINE = INNODB
  AUTO_INCREMENT = 2727
  DEFAULT CHARSET = UTF8;

# 20191127
create table DW_OPEN_DATASOURCE_CONFIG
(
    ID              INT PRIMARY KEY AUTO_INCREMENT COMMENT '自增ID',
    CONNECTION_NAME VARCHAR(32) COMMENT '连接名称',
    DB_TYPE         INT COMMENT '数据库类型ID',
    DB_NAME         VARCHAR(64) COMMENT '数据库名称',
    DB_HOST         VARCHAR(256) COMMENT '数据库地址',
    DB_PORT         INT COMMENT '数据库端口',
    DB_USERNAME     VARCHAR(64) COMMENT '数据库用户名',
    DB_PASSWORD     VARCHAR(64) COMMENT '数据库密码',
    ZK_NODE         VARCHAR(64) COMMENT 'ZOOKEEPER节点',
    CREATE_TIME     DATETIME COMMENT '创建时间',
    UPDATE_TIME     DATETIME COMMENT '更新时间'
);

alter table DW_OPEN_DATASOURCE_CONFIG
    add column PARENT_ID INT COMMENT '父配置ID';
alter table DW_OPEN_DATASOURCE_CONFIG
    add column CHILDREN_ID INT COMMENT '子配置ID';

CREATE TABLE DW_OPEN_DATABASE
(
    ID                INT PRIMARY KEY AUTO_INCREMENT COMMENT '自增ID',
    DATABASE_NAME     VARCHAR(32) COMMENT '数据库名称',
    DRIVER_CLASS_NAME VARCHAR(128) COMMENT '驱动类名',
    CREATE_TIME       DATETIME COMMENT '创建时间',
    UPDATE_TIME       DATETIME COMMENT '更新时间',
    PIC_URL           VARCHAR(128) COMMENT '图片地址'
);

CREATE TABLE DW_OPEN_API_GROUP
(
    `ID`          INT PRIMARY KEY AUTO_INCREMENT COMMENT '自增ID',
    `GROUP_NAME`  VARCHAR(64) COMMENT 'API分组名称',
    `CREATE_USER` VARCHAR(64) COMMENT '创建用户',
    `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
    `UPDATE_TIME` DATETIME DEFAULT NULL COMMENT '更新时间'
) ENGINE = INNODB;


alter table DW_OPEN_DATA_ASSET_API
    ADD COLUMN DATASOURCE_CONFIG_ID INT COMMENT '数据源配置ID';



ALTER TABLE DW_OPEN_APP_ACCESS
    ADD COLUMN USERNAME VARCHAR(32) COMMENT '用户名';


CREATE TABLE `DW_OPEN_COLLECT`
(
    `ID`                int(11) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
    `USERNAME`          varchar(32) DEFAULT NULL COMMENT '用户名',
    `DATA_ASSET_API_ID` int(11)     DEFAULT NULL COMMENT '资产ID',
    `CREATE_TIME`       datetime    DEFAULT NULL COMMENT '创建时间',
    `UPDATE_TIME`       datetime    DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (`ID`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8
 